### PR TITLE
auto sync 2023-01-08-20-06

### PR DESCRIPTION
**Pull request by nunnatsa**
auto sync upstream 2023-01-08-20-06

### CODE REVIEW

**Comment by davidvossel** [comment]
The capk image is not being used that's built for this PR. instead the prerelease one is being used.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-kubevirt/40/pull-ci-openshift-cluster-api-provider-kubevirt-main-cluster-api-provider-kubevirt-with-hypershift/1612178950325276672/artifacts/cluster-api-provider-kubevirt-with-hypershift/hypershift-e2e/artifacts/TestCreateCluster_PreTeardownClusterDump/namespaces/e2e-clusters-jk5vt-example-r9qmt/apps/deployments/capi-provider.yaml

```
   fieldPath: metadata.namespace
        image: registry.ci.openshift.org/hypershift/cluster-api-kubevirt-controller:0.0.1-prerelease
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
```

**Comment by nunnatsa** [comment]
Running again, after the test fix was merged:
/test cluster-api-provider-kubevirt-with-hypershift

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

Thanks!

**Pull request merged**
